---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: apache-server
    groups:
     - server
    image: "debian:buster-slim"
    pre_build_image: false
    published_ports:
      - 0.0.0.0:${APACHE_PORT:-80}:80
  - name: apache-client
    groups:
     - client
    image: "ansible/centos7-ansible:latest"
    command: init
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
